config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :companies do

    get :alldocuments, to: 'companies#alldocuments'


    resources :folders do
      resources :documents do
        collection do
          get :newfolder , to: 'documents#newfolder'
          post :newfolder , to: 'documents#createfolder'
          delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
          get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
          match 'newfolder/:id(.:format)', :via => :put, :to => 'documents#updatefolder'
          match 'newfolder/:id(.:format)', :via => :patch,:to => 'documents#updatefolder'
          post :sortfile
          post :sortfolder
        end
      end

    end

    resources :documents do
      collection do
        get :newfolder
        post 'newfolder', to: 'documents#createfolder'
        delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
        get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
        put 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        patch 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        post :sortfile
        post :sortfolder
      end
    end
    resources :company_infos
    resources :contact_people

  end

  get '' , to: 'companies#index'
  get 'signin' , to: 'session#new'
  post 'signin' , to: 'session#create'
  delete 'signout' , to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/views/admins/_form.html.erb
<%= form_for admin, html: {class: :well} do |f| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Full_name %>
    <%= f.text_field :admin_fullname, class: "form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :Email_Address %>
      <%= f.text_field :admin_email, class: "form-control" %>
    </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :Retype_Password_Again %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  <div class="submit">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>EDIT ADMIN</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">


          <%= render 'form', admin: @admin %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
        <div class="well">
          <%= link_to '<span class="glyphicon  glyphicon-eye-open"></span> Show'.html_safe, @admin, class: "btn btn-primary btn-block " %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, admins_path , class: "btn btn-primary btn-block " %>
        </div>

        </div>


      </div>


    </div>




  </div>



</div>

app/views/admins/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>ADMINS</strong> </h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <% if  !notice.nil? %>
        <div class="alert alert-info" id="notice">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
    <% end %>


    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-7 ">
        <div class="card-1 ">

<table class="table table-striped well">
  <thead>
    <tr>
      <th>Admin Full Name</th>
      <th>Admin Email</th>
      <th colspan="3" style="text-align: center"> Action</th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.admin_fullname %></td>
        <td><%= admin.admin_email %></td>
        <td colspan="3"><%= link_to '<span class="btn btn-circle btn-success glyphicon  glyphicon-eye-open"></span>'.html_safe, admin %>
          <%= link_to '<span class="btn btn-circle btn-primary glyphicon  glyphicon-edit"></span>'.html_safe,   edit_admin_path(admin) %>
          <%= link_to '<span class="btn btn-circle btn-danger glyphicon  glyphicon-remove"></span>'.html_safe, admin, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
          </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-5 ">

<div class="card-1" >
        <h3 class="text-center" ><strong>MENU</strong></h3>
        <hr>
  <div class="well">

        <%= link_to '<span class="glyphicon  glyphicon-plus"></span> New Admin'.html_safe, new_admin_path, html_option={ class: "btn btn-primary btn-block "} %>

  </div>
</div>
      </div>_

      </div>
  </div>
</div>

app/views/admins/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>NEW ADMIN</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

          <%= render 'form', admin: @admin %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>

          <hr>
        <div class="well">
          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, admins_path , class: "btn btn-primary btn-block " %>
        </div>


        </div>


      </div>


    </div>




  </div>



</div>

app/views/admins/show.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>SHOW ADMIN</strong> </h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <% if  !notice.nil? %>
        <div class="alert alert-info" id="notice">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-7 ">
        <div class="card-1">
          <strong>Admin fullname: </strong>
        <p class="well well-sm">

  <%= @admin.admin_fullname %>
      </p>
          <strong>Admin email: </strong>
<p class="well well-sm">

  <%= @admin.admin_email %>
</p>
          <strong>Created Time: </strong>
          <p class="well well-sm">

            <%= @admin.created_at.strftime "%d %B %Y , %I:%M %P" %>
          </p>

          <strong>Updated Time: </strong>
          <p class="well well-sm">

            <%= @admin.created_at.strftime "%d %B %Y , %I:%M %P" %>
          </p>
        </div>
      </div>
      <div class="col-md-4 col-sm-5">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
<div class="well">
          <%= link_to '<span class="glyphicon  glyphicon-edit"></span> Edit contact'.html_safe,  edit_admin_path(@admin), html_option={ class: "btn btn-primary btn-block "} %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, admins_path, class: "btn btn-primary btn-block " %>

</div>
        </div>

      </div>


      </div>
  </div>
</div>