config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :companies do

    get :alldocuments, to: 'companies#alldocuments'


    resources :folders do
      resources :documents do
        collection do
          get :newfolder , to: 'documents#newfolder'
          post :newfolder , to: 'documents#createfolder'
          delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
          get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
          match 'newfolder/:id(.:format)', :via => :put, :to => 'documents#updatefolder'
          match 'newfolder/:id(.:format)', :via => :patch,:to => 'documents#updatefolder'
          post :sortfile
          post :sortfolder
        end
      end

    end

    resources :documents do
      collection do
        get :newfolder
        post 'newfolder', to: 'documents#createfolder'
        delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
        get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
        put 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        patch 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        post :sortfile
        post :sortfolder
      end
    end
    resources :company_infos
    resources :contact_people

  end

  get '' , to: 'companies#index'
  get 'signin' , to: 'session#new'
  post 'signin' , to: 'session#create'
  delete 'signout' , to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/document.rb
class Document < ApplicationRecord

	belongs_to :folders , optional:true 
	belongs_to :company

	mount_uploader :document_link, DocumentUploader
	validates_presence_of :document_link


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authorize
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :set_company, only: [:index, :new, :create, :show, :edit, :update, :destroy, :newfolder, :createfolder ,:destroyfolder, :editfolder, :updatefolder]
  before_action :set_current_folder, only: [:index, :new, :create, :show, :edit, :update, :destroy , :newfolder, :createfolder, :destroyfolder , :editfolder, :updatefolder]
   before_action :set_folder, only: [:destroyfolder, :editfolder, :updatefolder]
  # GET /documents
  # GET /documents.json
  def index
    if params.has_key?(:folder_id)
      
       
    @folders=@company.folders.where(folder_id: @current_folder.id ).order(:folders_position)
    @documents = @company.documents.where(folder_id: @current_folder.id).order(:document_position)
   
    else 

    @folders=@company.folders.where("folder_id IS NULL").order(:folders_position)
    @documents = @company.documents.where("folder_id IS NULL").order(:document_position)
   

    end

  if (params["format"]=="json")
      dochas=@documents.as_json
      folderhas=@folders.as_json

      dochas.each_with_index do |document,index|

        unless document["folder_id"].nil?

          dochas[index][:url]=company_folder_document_url(@company,document["folder_id"],document["id"],format: :json)
          dochas[index][:folder_url]=company_folder_documents_url(@company,document["folder_id"],format: :json)

        else

          dochas[index][:url]=company_document_url(@company,document["id"],format: :json)
          dochas[index][:folder_url]=company_documents_url(@company,format: :json)
        end


      end

      folderhas.each_with_index do |folder,index|
        folderhas[index][:url]=company_folder_documents_url(@company,folder["id"], format: :json)

        unless folder["folder_id"].nil?


          folderhas[index][:parrent_folder_url]=company_folder_documents_url(@company,folder["folder_id"],format: :json)

        else


          folderhas[index][:parrent_folder_url]=company_documents_url(@company,format: :json)
        end



      end

      procceddata=Hash.new
      if @current_folder
      unless @current_folder.folder_id.nil?
        procceddata["parent_folder_url"]=company_folder_documents_url(@company,@current_folder.folder_id, format: :json)

      else
        procceddata["parent_folder_url"]=company_documents_url(@company, format: :json)
      end
      end


    procceddata["documents"]=dochas
    procceddata["subfolders"]=folderhas

    render json: JSON.generate(procceddata)
  end
    
  end

  # GET /documents/1
  # GET /documents/1.json
  def show

    
  end

  def sortfolder
  pos=1

  params[:sortfolder].each do |foldersort|
  folder=Folder.find(foldersort) 
  folder.folders_position=pos
  folder.save
  pos+=1
    end  
  
  render plain: "successfully sorted"

  end

  def sortfile
 pos=1

  params[:sortdoc].each do |docsort|
  document=Document.find(docsort) 
  document.document_position=pos
  document.save
  pos+=1
    end  
  
  render plain: "successfully sorted file"
  end

  # GET /documents/newd
  def new
    @document = Document.new
  end

   def newfolder
    @folder = Folder.new
  end

def createfolder
    @folder = Folder.new(folder_params)
    @folder.company=@company 
    if params.has_key?(:folder_id)

    @folder.folder=@current_folder 
   
    end 

     if params.has_key?(:folder_id)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to company_folder_documents_path(@company,@current_folder), notice: 'Document was successfully created.' }
      
      else
        format.html { render :new }
      end
    end
  
      else

    respond_to do |format|
      if @folder.save
        format.html { redirect_to company_documents_path(@company), notice: 'Document was successfully created.' }
      
      else
        format.html { render :new }
      end
    end
  end


  end

  # GET /documents/1/edit
  def edit
  end

  def editfolder
  end

  # POST /documents
  # POST /documents.json
  def create
    @file=params[:document_link];
    @document = Document.new(document_params)
    @document.company=@company 
    if params.has_key?(:folder_id)

    @document.folder_id=@current_folder.id 
   
    end 

  

    respond_to do |format|
      if @document.save
            if params.has_key?(:folder_id)

    
      format.html { redirect_to [@company,@current_folder,:documents], notice: 'Document was successfully created.' }

      format.json { render :show, status: :created, location: [@company,@current_folder,:documents] }
          else 

      format.html { redirect_to [@company,:documents], notice: 'Document was successfully created.' }
      format.json { render :show, status: :created, location: [@company,:documents] }

            end

      
      else
        format.html { render :new }
        format.json { render json: [@company, @document].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update

    respond_to do |format|
      if @document.update(document_params)
         if params.has_key?(:folder_id)

    
      format.html { redirect_to [@company,@current_folder,:documents], notice: 'Document was successfully updated.' }
      format.json { render :show, status: :ok, location: [@company,@current_folder,:documents] }

         else

      format.html { redirect_to [@company,:documents], notice: 'Document was successfully updated.' }
      format.json { render :show, status: :ok, location: [@company,:documents] }

         end

      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

    def updatefolder
    respond_to do |format|
      if @folder.update(folder_params)
         if params.has_key?(:folder_id)

    
      format.html { redirect_to [@company,@current_folder,:documents], notice: 'Document was successfully updated.' }
          else 

      format.html { redirect_to [@company,:documents], notice: 'Document was successfully updated.' }
   
           end 

        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /documents/1
  # DELETE /documents/1.json'

  def destroy
    @document.destroy
      respond_to do |format|
           if params.has_key?(:folder_id)

    
      format.html { redirect_to company_folder_documents_url(@company,@current_folder) , notice: 'Document was successfully updated.' }
          else 

      format.html { redirect_to company_documents_url(@company), notice: 'Document was successfully updated.' }
   
           end 
    end
  end

   def destroyfolder
    @folder.destroy
    respond_to do |format|
        if params.has_key?(:folder_id)

    
      format.html { redirect_to company_folder_documents_url(@company,@current_folder) , notice: 'Document was successfully updated.' }
      format.json { render :show, status: :created, location: company_folder_documents_url(@company,@current_folder) }


        else

      format.html { redirect_to company_documents_url(@company), notice: 'Document was successfully updated.' }
      format.json { render :show, status: :created, location: company_documents_url(@company) }

        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end
      def set_folder
      @folder = Folder.find(params[:id])
    end
     def set_company
      @company = Company.find(params[:company_id])
    end

    def set_current_folder
          if params[:folder_id].present?
    
      @current_folder = Folder.find(params[:folder_id])

           end
    end

   def folder_params
      params.require(:folder).permit(:company_id, :folder_id, :folder_name )
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:company_id, :folder_id, :document_name, :document_link , :document_description)
    end









end

app/views/documents/_form.html.erb
 <div class="well">
  <% if defined? @current_folder %>

<%= form_for([@company,@current_folder,@document]) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="form-group">
    <%= f.label :document_name %>
    <%= f.text_field :document_name, class: "form-control"  %>

  </div>
    <div class="form-group">
    <%= f.label :document_description %>
    <%= f.cktext_area :document_description %>

  </div >
   <div class="form-group">
    <%= f.label :Document %>
    <%= f.file_field :document_link, class: "form-control"  %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% else %>

<%= form_for([@company, @document]) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="form-group">
    <%= f.label :Document_Name %>
    <%= f.text_field :document_name, class: "form-control"  %>

  </div>
      <div class="form-group">
    <%= f.label :document_description %>
    <%= f.text_area :document_description, class: "form-control" %>

  </div>
   <div class="form-group">
    <%= f.label :Document %>
    <%= f.file_field :document_link, class: "form-control"  %>

  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
  <% end %>

<% end %>
 </div>

app/views/documents/_form_editfolder.html.erb
<div class="well">

  <%
  if defined? @current_folder %>

<%= form_for @folder , url: "/companies/"+@company.id.to_s+"/folders/"+@current_folder.id.to_s+"/documents/newfolder/"+@folder.id.to_s do |f| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :Folder_name %>
    <%= f.text_field :folder_name, class: "form-control"  %>

  </p>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

<% else %>

<%= form_for @folder, url: "/companies/"+@company.id.to_s+"/documents/newfolder/"+@folder.id.to_s   do |f| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :Folder_Name %>
    <%= f.text_field :folder_name, class: "form-control"  %>

  </p>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
  <% end %>

<% end %>
</div>

app/views/documents/_form_newfolder.html.erb
<div class="well">
  <% if defined? @current_folder %>

<%= form_for @folder , url: newfolder_company_folder_documents_path(@company,@current_folder,@folder) do |f| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :Folder_name %>
    <%= f.text_field :folder_name, class: "form-control"  %>

  </p>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

<% else %>

<%= form_for @folder, url: newfolder_company_documents_path(@company,@folder)  do |f| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :Folder_Name %>
    <%= f.text_field :folder_name, class: "form-control"  %>

  </p>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
  <% end %>

<% end %>
</div>

app/views/documents/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>EDIT DOCUMENT</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

          <%= render 'form', document: @document %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
          <div class="well">
          <% unless  @current_folder %>

              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_documents_path(@company) , class: "btn btn-primary btn-block " %>

          <% else %>
              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_folder_documents_path(@company,@current_folder) , class: "btn btn-primary btn-block " %>

          <% end %>
            </div>

    </div>



        </div>


      </div>


    </div>




  </div>



</div>

app/views/documents/editfolder.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>EDIT FOLDER</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

          <%= render 'form_editfolder', folder: @folder %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
          <div class="well">
          <% unless  @current_folder %>

              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_documents_path(@company) , class: "btn btn-primary btn-block " %>

          <% else %>
              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_folder_documents_path(@company,@current_folder) , class: "btn btn-primary btn-block " %>

          <% end %>
            </div>

        </div>


      </div>


    </div>




  </div>



</div>

app/views/documents/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>DOCUMENTS</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
<div class="container-fluid">
<div class="row">
<div class="col-md-8">



<div class="card-1">

  <div class="panel-heading"> <h4>
    <% if params[:folder_id].present? %>
         <%= 'Drectory: '+@current_folder.folder_name  %>
        <% else %>
        Drectory: root
        <%  end %>
  </h4>
    <hr>
<ul class="list-group well well-sm " id="sortable_folder">
  <% @folders.each do |folder| %>
  <li class="ui-state-default list-group-item"  pos="sortfolder_<%= folder.id %>" > <h4>
<%= link_to  '<span class="glyphicon glyphicon-folder-open
" aria-hidden="true"></span> &nbsp'.html_safe+folder.folder_name , company_folder_documents_path(@company.id,folder) %>

 <small class="pull-right">
     <%= link_to '<span class="glyphicon glyphicon-remove
"></span>'.html_safe, "documents/newfolder/"+folder.id.to_s  ,:class => "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>

   <%= link_to '<span class="glyphicon glyphicon-edit
"></span>'.html_safe, "documents/newfolder/"+folder.id.to_s+"/edit"  ,:class => "btn btn-primary btn-sm" %>
   </small>
 
   </h4>
   </li>

   <% end %>

 

</ul>

<ul class="list-group well well-sm " id="sortable_document">
<% @documents.each do |document| %>
  <li class="list-group-item ui-state-default" pos="sortdoc_<%= document.id %>">
  <h4><span class="glyphicon glyphicon-file
" aria-hidden="true"></span>
<%= document.document_name %>
<small class="pull-right">
  <a href="<%= document.document_link %>" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon glyphicon-download-alt
"></span></a>
  <%= link_to '<span class="glyphicon  glyphicon-eye-open"></span>'.html_safe, company_document_path(@company,document) ,:class => "btn btn-success btn-sm"  %>

  <%= link_to '<span class="glyphicon glyphicon glyphicon-edit
"></span>'.html_safe, edit_company_document_path(@company.id,document) ,:class => "btn btn-primary btn-sm" %>
<%= link_to '<span class="glyphicon glyphicon glyphicon-remove
"></span>'.html_safe, company_document_path(@company.id,document),:class => "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>

</small>
</h4>
</li>
   <% end %>
</ul>


</div>

</div>
</div>

<div class="col-md-4">
  <div class="card-1">
    <h3 class="text-center" ><strong>MENU</strong></h3>
    <hr>
    <div class="well">
  <% if params[:folder_id].present? %>

      <% unless @current_folder.folder_id.nil? %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left
"></span> Back'.html_safe , company_folder_documents_path(@company.id,@current_folder.folder_id),:class => "btn btn-primary btn-block" %>

      <% else %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left
"></span> Back'.html_safe , company_documents_path(@company.id), :class => "btn btn-primary btn-block"%>
      <% end %>

  <% end %>


  <% unless defined? @current_folder %>
      <%= link_to '<span class="glyphicon glyphicon-file
" aria-hidden="true"></span> New Document'.html_safe, new_company_document_path(@company) ,:class => "btn btn-primary btn-block" %>

  <% else %>
      <%= link_to '<span class="glyphicon glyphicon-file
" aria-hidden="true"></span> New Document'.html_safe, new_company_folder_document_path(@company,@current_folder) ,:class => "btn btn-primary btn-block" %>

  <% end %>

  <% unless defined? @current_folder %>
      <%= link_to '<span class="glyphicon glyphicon-folder-open"> </span> &nbsp New Folder '.html_safe, newfolder_company_documents_path(@company),:class => "btn btn-primary btn-block"  %>

  <% else %>
      <%= link_to '<span class="glyphicon glyphicon-folder-open"> </span> &nbsp New Folder '.html_safe, newfolder_company_folder_documents_path(@company,@current_folder) ,:class => "btn btn-primary btn-block" %>

  <% end %>
</div>
</div>
</div>
</div>
</div>
</div>

<% unless defined? @current_folder %>
<script>
   var filesort="<%= sortfile_company_documents_path(@company) %> ";
var foldersort="<%= sortfolder_company_documents_path(@company) %>" ;
</script>
<% else %>
<script>
 var filesort="<%= sortfile_company_folder_documents_path(@company,@current_folder) %> ";
var foldersort="<%= sortfolder_company_folder_documents_path(@company,@current_folder) %> " ;

</script>
<% end %>



<script>    



$(function() {

        $( "#sortable_document" ).sortable({ 
            placeholder: "ui-sortable-placeholder",
            update: function (event, ui)
            {        

              var info = $(this).sortable( "serialize", {attribute : "pos"});

                $.ajax({
                    url: filesort,
                    type: 'POST',
                    data: info,

                })
                .done(function(data) {
               
                        console.log(data);
                })
                .fail(function() {
                   
                });
                
                

            }
        });
    });
    </script>


<script>    $(function() {
        $( "#sortable_folder" ).sortable({ 
            placeholder: "ui-sortable-placeholder",
            update: function (event, ui)
            {        

              var info = $(this).sortable( "serialize", {attribute : "pos"});

                $.ajax({
                    url: foldersort,
                    type: 'POST',
                    data: info,

                })
                .done(function(data) {
               console.log(data);
             
                })
                .fail(function() {
                   
                });
                
                

            }
        });
    });
    </script>

app/views/documents/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>NEW DOCUMENT</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

<%= render 'form', document: @document %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
          <div class="well">
          <% unless  @current_folder %>

          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_documents_path(@company) , class: "btn btn-primary btn-block " %>

          <% else %>
              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_folder_documents_path(@company,@current_folder) , class: "btn btn-primary btn-block " %>

              <% end %>
</div>
        </div>


      </div>


    </div>




  </div>



</div>

app/views/documents/newfolder.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3><strong>NEW FOLDER</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

          <%= render 'form_newfolder', folder: @folder %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
          <div class="well">
          <% unless  @current_folder %>

              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_documents_path(@company) , class: "btn btn-primary btn-block " %>

          <% else %>
              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_folder_documents_path(@company,@current_folder) , class: "btn btn-primary btn-block " %>

          <% end %>
            </div>

        </div>


      </div>


    </div>




  </div>



</div>

app/views/documents/show.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3> <strong>SHOW  DOCUMENT INFORMATION</strong> </h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <% if  !notice.nil? %>
        <div class="alert alert-info" id="notice">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-7 ">
        <div class="card-1">
          <strong>Document Name </strong>
 <p class="well well-sm"><%= @document.document_name %>  </p>
          <strong>Document Description</strong>
          <div class="well well-sm">  <%= @document.document_description.to_s.html_safe %>  </div>
          <Strong>Document size </Strong>
          <p class="well well-sm">  <%= @document.document_size %></p>
          <strong>Document Type</strong>
          <p class="well well-sm"> <%= @document.document_type %> </p>
          <Strong>Document url </strong>
          <p class="well well-sm"><%= @document.document_link %>  </p>


          </div>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-5 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>
          <hr>
          <div class="well">
          <% unless  @current_folder %>

              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_documents_path(@company) , class: "btn btn-primary btn-block " %>

          <% else %>
              <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, company_folder_documents_path(@company,@current_folder) , class: "btn btn-primary btn-block " %>

          <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>