config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :companies do

    get :alldocuments, to: 'companies#alldocuments'


    resources :folders do
      resources :documents do
        collection do
          get :newfolder , to: 'documents#newfolder'
          post :newfolder , to: 'documents#createfolder'
          delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
          get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
          match 'newfolder/:id(.:format)', :via => :put, :to => 'documents#updatefolder'
          match 'newfolder/:id(.:format)', :via => :patch,:to => 'documents#updatefolder'
          post :sortfile
          post :sortfolder
        end
      end

    end

    resources :documents do
      collection do
        get :newfolder
        post 'newfolder', to: 'documents#createfolder'
        delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
        get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
        put 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        patch 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        post :sortfile
        post :sortfolder
      end
    end
    resources :company_infos
    resources :contact_people

  end

  get '' , to: 'companies#index'
  get 'signin' , to: 'session#new'
  post 'signin' , to: 'session#create'
  delete 'signout' , to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/company.rb
class Company < ApplicationRecord
	has_many :folders
	has_many :documents
	has_many :contact_persons
	has_many :company_infos
	validates :company_name, presence: true


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authorize
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  layout :false, except: [:edit,:show]
  layout "root", except: [:edit,:show]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    randomstring = (0...10).map { o[rand(o.length)] }.join
    @company = Company.new(company_params)
    @company.token=randomstring
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def alldocuments 



render json: JSON.generate(alldocs)

  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name)
    end



    def alldocs  


    alldoc=Document.where(company_id: params[:company_id]).order(:document_position).as_json

    allfolder=Folder.where(company_id: params[:company_id]).order(:folders_position).as_json

    alldoc.each_with_index do |document,index|

      unless document["folder_id"].nil?

        alldoc[index][:url]=company_folder_document_url(params[:company_id],document["folder_id"],document["id"],format: :json)
        alldoc[index][:folder_url]=company_folder_documents_url(params[:company_id],document["folder_id"],format: :json)

      else

        alldoc[index][:url]=company_document_url(params[:company_id],document["id"],format: :json)
        alldoc[index][:folder_url]=company_documents_url(params[:company_id],format: :json)
      end


    end

    allfolder.each_with_index do |folder,index|
      allfolder[index][:url]=company_folder_documents_url(params[:company_id],folder["id"], format: :json)

      unless folder["folder_id"].nil?


        allfolder[index][:parrent_folder_url]=company_folder_documents_url(params[:company_id],folder["folder_id"],format: :json)

      else


        allfolder[index][:parrent_folder_url]=company_documents_url(params[:company_id],format: :json)
      end



    end

    procceddata=Hash.new 

    procceddata["documents"]=alldoc.select { |a| a["folder_id"].nil? }  
    procceddata["subfolders"]=procedure alldoc,allfolder
  
      return procceddata

    end





    def procedure documents,folders,parent=nil

   
  pfolders=folders.select { |a| a["folder_id"]==parent }  
  subfolders=folders.reject { |a| a["folder_id"]==parent }

  

    pfolders.each_with_index  do |pfolder, index| 
    pfolders[index]["documents"]=documents.select { |a| a["folder_id"]==pfolder["id"]}
    documents=folders.reject { |a| a["folder_id"]==pfolder["id"] }
    pfolders[index]["subfolders"]=procedure(documents,subfolders,pfolder["id"])


  end

  return pfolders
  

  end


end

app/views/companies/_form.html.erb
<%= form_for company,html: {class: :well} do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form-group">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name, class: "form-control" %>
  </div>
  <br>
  <div class="submit">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 > <strong>EDIT COMPANY/CLIENTS : </strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">


          <%= render 'form', company: @company %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>

          <hr>

          <%= link_to '<span class="glyphicon  glyphicon-eye-open"></span> Show'.html_safe, @company, class: "btn btn-primary btn-block " %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, companies_path , class: "btn btn-primary btn-block " %>


        </div>


      </div>


    </div>




  </div>



</div>

app/views/companies/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>COMPANIES/CLIENTS OF APP </strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <% if  !notice.nil? %>
        <div class="alert alert-info" id="notice">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
    <% end %>


    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-7 ">
<div class="card-1">


<table class="table table-striped well">
  <thead>
    <tr>
      <th>company id</th>
      <th>company Name</th>
      <th>Action</th>
    </tr>
    </tr>
  </thead>

  <tbody border="1px">
  <tr>


    <% @companies.each do |company| %>
      <tr>
        <td><%= company.id%></td>
        <td><%= company.company_name%></td>
        <td colspan="3"><%= link_to '<span class="btn btn-circle btn-success glyphicon  glyphicon glyphicon-open"></span>'.html_safe, company_path(company)  %>
          <%= link_to '<span class="btn btn-circle btn-primary glyphicon  glyphicon-edit"></span>'.html_safe,  edit_company_path(company) %>
          <%= link_to '<span class="btn btn-circle btn-danger glyphicon  glyphicon-remove"></span>'.html_safe, company, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>
  </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-5  ">
  <div class="card-1">

    <h3 class="text-center" ><strong>MENU</strong></h3>        <hr>

        <%= link_to '<span class="glyphicon  glyphicon-plus"></span> New Client/Company'.html_safe, new_company_path, html_option={ class: "btn btn-primary btn-block "} %>

        <br>
  </div>
      </div>_


    </div>
  </div>
</div>

app/views/companies/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 ><strong>NEW COMPANY</strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ">
        <div class="card-1">

          <%= render 'form', company: @company %>
        </div>

      </div>
      <div class="col-md-4 ">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>        <hr>


          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, companies_path , class: "btn btn-primary btn-block " %>



        </div>


      </div>


    </div>




  </div>



</div>

app/views/companies/show.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3 > <strong>SHOW COMPANY/CLIENT : </strong></h3>
    </div>
  </div>
</nav>
<div id="main-content">
  <div class="container-fluid">
    <% if  !notice.nil? %>
        <div class="alert alert-info" id="notice">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-7 ">
        <div class="card-1">
          <strong>
            Company Name:
          </strong>
<p class="well well-sm" >


    <%= @company.company_name %>

</p>
          <strong>
            Company Token:
          </strong>
          <p class="well well-sm" >


    <%= @company.token %>

</p>
          <strong>Created Time: </strong>


          <p class="well well-sm ">
            <%= @company.created_at.strftime "%d %B %Y , %I:%M %P" %>
          </p>

          <strong>Updated Time: </strong>
          <p class="well well-sm">

            <%= @company.created_at.strftime "%d %B %Y , %I:%M %P" %>
          </p>
</div></div>
      <div class="col-md-4 col-sm-3">
        <div class="card-1">
          <h3 class="text-center" ><strong>MENU</strong></h3>

          <hr>
      <div class="well ">
          <%= link_to '<span class="glyphicon  glyphicon-edit"></span> Edit Company/Clients'.html_safe,  edit_company_path(@company), html_option={ class: "btn btn-primary btn-block "} %>
          <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, companies_path, class: "btn btn-primary btn-block " %>

      </div>
        </div>

      </div>

    </div>
  </div>
</div>