config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :companies do

    get :alldocuments, to: 'companies#alldocuments'


    resources :folders do
      resources :documents do
        collection do
          get :newfolder , to: 'documents#newfolder'
          post :newfolder , to: 'documents#createfolder'
          delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
          get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
          match 'newfolder/:id(.:format)', :via => :put, :to => 'documents#updatefolder'
          match 'newfolder/:id(.:format)', :via => :patch,:to => 'documents#updatefolder'
          post :sortfile
          post :sortfolder
        end
      end

    end

    resources :documents do
      collection do
        get :newfolder
        post 'newfolder', to: 'documents#createfolder'
        delete 'newfolder/:id(.:format)', to: 'documents#destroyfolder'
        get 'newfolder/:id(.:format)/edit', to: 'documents#editfolder'
        put 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        patch 'newfolder/:id(.:format)', to: 'documents#updatefolder'
        post :sortfile
        post :sortfolder
      end
    end
    resources :company_infos
    resources :contact_people

  end

  get '' , to: 'companies#index'
  get 'signin' , to: 'session#new'
  post 'signin' , to: 'session#create'
  delete 'signout' , to: 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cms</title>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="nav-side-menu">
    <div class="brand"><b>CONTENT MANAGEMENT</b>  </div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

    <div class="menu-list">

      <ul id="menu-content" class="menu-content collapse out">
        <li>
          <a href="<%= company_path(@company) %>">
            <i class="fa fa-dashboard fa-lg"></i> <b> <%= @company.company_name %></b>
          </a>
        </li>
        <li>
          <a href="<%= company_contact_people_path(@company) %>">
            <i class="fa fa-book" aria-hidden="true"></i>

            Contact Person
          </a>
        </li>
        <li>
          <a href="<%= company_company_infos_path(@company) %>">
            <i class="fa fa-info fa-lg"></i> Company Information
          </a>
        </li>
        <li>
          <a href="<%= company_documents_path(@company) %>">
            <i class="fa fa-file fa-lg"></i> Documents
          </a>
        </li>

        <br>
        <br>
        <li>
          <a href="<%= companies_path %>">
            <i class="fa fa-database fa-lg"></i>Client | Company
          </a>
        </li>
        <li>
          <a href="<%= admins_path %>">
            <i class="fa fa-unlock fa-lg"></i> Admin
          </a>
        </li>
        <li>

          <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Log out'.html_safe, signout_path, method: :delete, data: { confirm: 'Are you sure?' } %>

        </li>






      </ul>
    </div>
  </div>

  <div id="page-container">

    <%= yield %>

  </div>
  </body>
</html>

app/views/layouts/root.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cms</title>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="nav-side-menu">
  <div class="brand"><b>CONTENT MANAGMENT</b>

  </div>

  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

  <div class="menu-list">

    <ul id="menu-content" class="menu-content collapse out">

      <li>
        <a href="<%= companies_path %>">
          <i class="fa fa-database fa-lg"></i>
         Client | Company
        </a>
      </li>
      <li>
        <a href="<%= admins_path %>">
          <i class="fa fa-unlock fa-lg"></i> Admin
        </a>
      </li>

      <li>

      <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Log out '.html_safe+'('+@current_admin.admin_fullname+')' , signout_path, method: :delete, data: { confirm: 'Are you sure?' } %>

      </li>



    </ul>
  </div>
</div>

<div id="page-container">

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cms</title>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>